# Generated by Django 5.0.2 on 2024-02-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartStayApp', '0003_alter_hostel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
