# Generated by Django 5.0.2 on 2024-02-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartStayApp', '0005_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
