# Generated by Django 5.0.2 on 2024-02-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartStayApp', '0007_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(max_length=500),
        ),
    ]
