# Generated by Django 5.0.2 on 2024-02-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartStayApp', '0012_remove_booking_user_booking_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
